### PR TITLE
Added task to install package dependencies. Caters for different dist…

### PR DESCRIPTION
**Pull request by whitingjr**
…ributions.

### CODE REVIEW

**Comment by rvansa** [comment]
Generally OK, but I suggest we should adopt the latest JDK release available in given distribution, that means JDK 14 where applicable and JDK 11 on those that don't have JDK 14 available. In fedora there should be `java-latest-openjdk`, too.

**Comment by whitingjr** [comment]
I'll amend the Fedora/RedHat/CentOS distribution to use the latest as you suggest. Plus find the equivalent for Ubuntu. If it exists.

**Comment by whitingjr** [comment]
This does require the user to use `become: yes` when calling the role. Is that a concern ?

**Comment by rvansa** [comment]
Well it would be certainly more useful if you could run it without root access, since Java is most likely installed anyway.

**Comment by whitingjr** [comment]
> Well it would be certainly more useful if you could run it without root access, since Java is most likely installed anyway.

Not always installed. Nor is unzip.

**Comment by rvansa** [comment]
And can you make that conditional, requiring root only when Java/unzip is not installed?

**Comment by whitingjr** [comment]
> And can you make that conditional, requiring root only when Java/unzip is not installed?

 I don't know if that's possible.
 The hosts file will need to specify ansible_user=root or `become: yes` in the playbook. We are only in control of the role task file here.

**Comment by rvansa** [comment]
I am not too keen to run HF as root, which is a security risk (e.g. if there is a bug that lets you trick HF to store some file on any path - note that we don't have any connection credentials whatsover).
What about just testing if Java is present, spitting out a message 'Please run ansible-playbook -K install-java.yaml' and providing the install script separately?

**Comment by whitingjr** [comment]
Which is the same as doing nothing and letting hyperfoil_setup fail with an error like this.
```
TASK [hyperfoil.hyperfoil_setup : Unzip file] ************************************************************************************************************************************************************************************************************************************
fatal: [192.168.57.3]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/tmp/hyperfoil/hyperfoil-release-0.9.zip\". Make sure the required command to extract the file is installed. Command \"unzip\" not found. Command \"/usr/bin/tar\" could not handle archive."}
```

 The user will find out either way. I don't think this issue is going to progress so I'll close it.
 If you don't agree then open it again.

**Pull request closed without merging**
